### ISSUE TITLE
Feature Request: Improve output readability

### ISSUE THREAD

**Issue by log1-c** [zevenet/zevenet-monitoring-plugins#1]
Hello :)

first of all, thank you for the plugins, they work really well :)

I'd like to propose two little requests that, in my eyes, would improve the readability of the output.

1st:
when having multiple backends in the output there should be a separator between each Backend after the closing bracket and the word "Backend"

Example of current output:
```
ZEVENET CRITICAL - Backend='ip:12801' status='up' (established_connections='0') (pending_connections='0')Backend='ip:12801' status='maintenance' (established_connections='0') (pending_connections='0')Backend='ip:12801' status='maintenance' (established_connections='0') (pending_connections='0')
```
with separator:
```
ZEVENET CRITICAL - Backend='ip:12801' status='up' (established_connections='0') (pending_connections='0'), Backend='ip:12801' status='maintenance' (established_connections='0') (pending_connections='0'), Backend='ip:12801' status='maintenance' (established_connections='0') (pending_connections='0')
```

2nd proposal:
Display backends with Problems first in the output.
```
ZEVENET CRITICAL - Backend='ip:12801' status='maintenance' (established_connections='0') (pending_connections='0'), Backend='ip:12801' status='maintenance' (established_connections='0') (pending_connections='0'), Backend='ip:12801' status='up' (established_connections='0') (pending_connections='0')
```
Or make them otherwise a bit more prominent.

**Comment by adanmarin-zevenet** [comment]
Hello.

Regarding your first proposal "when having multiple backends in the output there should be a separator between each Backend after the closing bracket and the word "Backend"
we have already applied the commit.
https://github.com/zevenet/zevenet-monitoring-plugins/commit/13c4b754d9f47546a1d13ba3145156560a607b27

In the second proposal "Display backends with Problems first in the output." we can not make any changes, we show them as they are ordered in the configuration.

Thank you very much for the proposals we are glad to assist you.
Best regards.

**Comment by log1-c** [comment]
Thanks for the quick output improvement!
